# Select the base image that is best for our application
FROM python:3

# ADD THESE TWO LINES TO INSTALL CRON
RUN apt-get update
RUN apt-get install cron -y

#We set an environment variable so that Python prints things immediately
ENV PYTHONUNBUFFERED 1

# Set the working directory to copy stuff to
WORKDIR /app
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

# ADD THESE TWO LINES TO SET UP ROOT CRONTAB
RUN touch /var/spool/cron/crontabs/root
RUN crontab -l

CMD python manage.py crontab add && service cron start && python manage.py runserver "0.0.0.0:8001"
